import React from "react";
import Head from "next/head";

import ShortiesTable from "../../components/Table";

const Shorties: React.FC = () => {
  return (
    <>
      <Head>
        <title>My Shorties</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ShortiesTable />
    </>
  );
};

export default Shorties;
