import Head from "next/head";

import Form from "../components/Form";

export default function Home() {
  return (
    <main>
      <Head>
        <title>Shorty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form />
    </main>
  );
}
